title: Carson H. Franklin
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Carson H. Franklin
    tagline: Gen-X / Millenial Daywalker
    profile_img: images/cfcom-256.png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: About
        url: /about/
        style: link
      - label: Posts
        url: /blog/
        style: link
      - label: Tags
        url: /tags/
        style: link
      - label: Professional
        url: /professional/
        style: link
      - label: Music
        url: /music/
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/carsonhfranklin'
        style: icon
        icon_class: twitter
        new_window: true
      - label: GitHub
        url: 'https://github.com/FhlostonParadise'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/in/carsonfranklin/'
        style: icon
        icon_class: linkedin
        new_window: true
      - label: DEV
        url: 'https://dev.to/fhlostonparadise'
        style: icon
        icon_class: dev
        new_window: true
  footer:
    content: '&copy; Carson H Franklin. All rights reserved.'
  domain: 'https://carsonfranklin.com'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
disqusShortname: cfcom
googleAnalytics: G-VQVV918XGM
markup:
  goldmark:
    renderer:
      unsafe: true
